### ISSUE TITLE
Make this repository private

### ISSUE THREAD

**Issue by voidbert** [Cerqueira025/LI-3#1]
I don't know if you're aware, but this repository is public, and classmates like me are able to see it. If I'm mistaken and you're actually allowing me to lend some code, then thanks!

**Comment by Cerqueira025** [comment]
[like]  Ana Carolina Penha Cerqueira reacted to your message:
________________________________
From: Voidbert ***@***.***>
Sent: Wednesday, October 18, 2023 11:08:01 PM
To: Cerqueira025/LI-3 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Cerqueira025/LI-3] Make this repository private (Issue #1)


I don't know if you're aware, but this repository is public, and classmates like me are able to see it. If I'm mistaken and you're actually allowing me to lend some code, then thanks!
